const translations = {
vi:{nav_home:'Trang chủ',nav_about:'Giới thiệu',nav_services:'Dịch vụ',nav_partners:'Đối tác',nav_capabilities:'Năng lực',nav_contact:'Liên hệ',hero_badge:'Thương mại toàn cầu • Logistics • Xuất nhập khẩu',hero_title:'CÔNG TY L38',hero_subtitle:'Đối tác đáng tin cậy trong lĩnh vực xuất nhập khẩu và thương mại quốc tế',hero_cta:'Liên Hệ',hero_cta2:'Xem dịch vụ',stat_1:'Khách hàng',stat_2:'Đối tác quốc tế',stat_3:'Đơn hàng hỗ trợ',stat_4:'Hỗ trợ tư vấn',about_title:'Giới thiệu công ty',about_desc:'Công ty L38 hoạt động trong lĩnh vực xuất nhập khẩu, thương mại và kết nối đối tác quốc tế. Chúng tôi cam kết mang đến giải pháp giao thương minh bạch, hiệu quả và bền vững cho khách hàng và đối tác.',values_title:'Giá trị cốt lõi',value_1_title:'Uy tín',value_1_desc:'Cam kết minh bạch và đúng tiến độ trong từng giao dịch.',value_2_title:'Hiệu quả',value_2_desc:'Tối ưu quy trình vận hành và chi phí cho khách hàng.',value_3_title:'Bền vững',value_3_desc:'Hướng tới hợp tác lâu dài và phát triển quốc tế ổn định.',services_title:'Lĩnh vực hoạt động',service_1:'Dịch vụ xuất nhập khẩu hàng hóa trong và ngoài nước.',service_2:'Kết nối đối tác và phát triển thương mại quốc tế.',service_3:'Hỗ trợ vận chuyển và thủ tục xuất nhập khẩu.',partners_title:'Đối tác & Thị trường',partners_desc:'Kết nối chuỗi cung ứng linh hoạt và thương mại xuyên biên giới cho nhiều thị trường trọng điểm.',cap_title:'Năng lực công ty',cap_1_title:'Vận hành đơn hàng',cap_1_desc:'Quản lý tiến độ, điều phối giao nhận và xử lý đơn hàng xuyên biên giới.',cap_2_title:'Kết nối nhà cung cấp',cap_2_desc:'Tìm nguồn hàng, xác minh đối tác và tối ưu chuỗi cung ứng thực tế.',cap_3_title:'Hồ sơ & chứng từ',cap_3_desc:'Hỗ trợ chứng từ, thủ tục xuất nhập khẩu và phối hợp logistics.',cap_4_title:'Hỗ trợ đa ngôn ngữ',cap_4_desc:'Làm việc hiệu quả với khách hàng Việt Nam, Trung Quốc và quốc tế.',form_title:'Liên hệ nhanh',form_name:'Họ và tên',form_email:'Email',form_message:'Nội dung cần hỗ trợ',form_btn:'Gửi thông tin',form_note:'* Đổi your-form-id trong index.html để nhận email thật về hộp thư công ty.',contact_title:'Liên hệ',role_ceo:'Giám Đốc',role_cfo:'Giám Đốc Tài Chính',footer_desc:'Import Export Services & Trading Company Limited',footer_contact:'Liên hệ',footer_market:'Thị trường'},
en:{nav_home:'Home',nav_about:'About',nav_services:'Services',nav_partners:'Partners',nav_capabilities:'Capabilities',nav_contact:'Contact',hero_badge:'Global Trade • Logistics • Import Export',hero_title:'L38 COMPANY',hero_subtitle:'A trusted partner in import-export and international trade',hero_cta:'Contact Us',hero_cta2:'View Services',stat_1:'Clients',stat_2:'International Partners',stat_3:'Orders Supported',stat_4:'Consulting Support',about_title:'About Company',about_desc:'L38 specializes in import-export, trade, and international business connection. We are committed to transparent, efficient, and sustainable trading solutions.',values_title:'Core Values',value_1_title:'Credibility',value_1_desc:'Transparent cooperation and on-time execution.',value_2_title:'Efficiency',value_2_desc:'Optimized processes and cost-effective solutions.',value_3_title:'Sustainability',value_3_desc:'Long-term cooperation and stable international growth.',services_title:'Business Areas',service_1:'Import and export solutions for domestic and international goods.',service_2:'Partner matching and international trade development.',service_3:'Shipping support and customs/import-export procedures.',partners_title:'Partners & Markets',partners_desc:'Flexible supply chain connection and cross-border trade for key markets.',cap_title:'Company Capabilities',cap_1_title:'Order Operations',cap_1_desc:'Progress tracking, logistics coordination, and cross-border order execution.',cap_2_title:'Supplier Connection',cap_2_desc:'Sourcing, partner verification, and supply chain optimization.',cap_3_title:'Documentation',cap_3_desc:'Support for documents, import-export procedures, and logistics coordination.',cap_4_title:'Multilingual Support',cap_4_desc:'Efficient collaboration with Vietnamese, Chinese, and international clients.',form_title:'Quick Contact',form_name:'Full Name',form_email:'Email',form_message:'Your Message',form_btn:'Send Message',form_note:'* Replace your-form-id in index.html to receive real emails.',contact_title:'Contact',role_ceo:'Director',role_cfo:'Chief Financial Officer',footer_desc:'Import Export Services & Trading Company Limited',footer_contact:'Contact',footer_market:'Markets'},
zh:{nav_home:'首页',nav_about:'公司介绍',nav_services:'业务范围',nav_partners:'合作伙伴',nav_capabilities:'公司实力',nav_contact:'联系我们',hero_badge:'全球贸易 • 物流 • 进出口',hero_title:'L38 国际贸易公司',hero_subtitle:'值得信赖的进出口与国际贸易合作伙伴',hero_cta:'立即联系',hero_cta2:'查看服务',stat_1:'客户',stat_2:'国际合作伙伴',stat_3:'支持订单',stat_4:'咨询支持',about_title:'公司简介',about_desc:'L38 专注于进出口、国际贸易与跨境合作对接，为客户提供透明、高效、可持续的贸易解决方案。',values_title:'核心价值',value_1_title:'信誉',value_1_desc:'坚持透明合作，按时履约。',value_2_title:'效率',value_2_desc:'优化流程与成本，提高业务效率。',value_3_title:'长期合作',value_3_desc:'重视稳定、长期、可持续的发展。',services_title:'主营业务',service_1:'国内外货物进出口服务。',service_2:'国际合作伙伴对接与贸易拓展。',service_3:'物流运输及进出口手续支持。',partners_title:'合作伙伴与市场',partners_desc:'为重点市场提供灵活供应链连接与跨境贸易服务。',cap_title:'公司实力',cap_1_title:'订单运营',cap_1_desc:'订单进度管理、运输协调与跨境交付支持。',cap_2_title:'供应商对接',cap_2_desc:'供应商开发、合作审核与供应链优化。',cap_3_title:'单证与报关',cap_3_desc:'协助进出口单证、报关与物流协调。',cap_4_title:'多语言支持',cap_4_desc:'高效服务越南、中国及国际客户。',form_title:'快速联系',form_name:'您的姓名',form_email:'电子邮箱',form_message:'您的需求',form_btn:'发送信息',form_note:'* 请在 index.html 中替换 your-form-id，即可接收真实邮件。',contact_title:'联系我们',role_ceo:'总经理',role_cfo:'财务总监',footer_desc:'进出口服务与贸易有限公司',footer_contact:'联系方式',footer_market:'主要市场'},
hi:{nav_home:'होम',nav_about:'परिचय',nav_services:'सेवाएँ',nav_partners:'साझेदार',nav_capabilities:'क्षमताएँ',nav_contact:'संपर्क',hero_badge:'वैश्विक व्यापार • लॉजिस्टिक्स • आयात-निर्यात',hero_title:'L38 COMPANY',hero_subtitle:'आयात-निर्यात और अंतरराष्ट्रीय व्यापार में आपका विश्वसनीय साझेदार',hero_cta:'संपर्क करें',hero_cta2:'सेवाएँ देखें',stat_1:'ग्राहक',stat_2:'अंतरराष्ट्रीय साझेदार',stat_3:'समर्थित ऑर्डर',stat_4:'परामर्श सहायता',about_title:'कंपनी परिचय',about_desc:'L38 कंपनी आयात-निर्यात, व्यापार और अंतरराष्ट्रीय साझेदारी कनेक्शन में विशेषज्ञता रखती है। हम पारदर्शी, प्रभावी और टिकाऊ व्यापार समाधान प्रदान करने के लिए प्रतिबद्ध हैं।',values_title:'मुख्य मूल्य',value_1_title:'विश्वसनीयता',value_1_desc:'हर लेनदेन में पारदर्शिता और समयबद्ध निष्पादन।',value_2_title:'दक्षता',value_2_desc:'ग्राहकों के लिए प्रक्रियाओं और लागत का अनुकूलन।',value_3_title:'स्थिरता',value_3_desc:'दीर्घकालिक सहयोग और स्थिर अंतरराष्ट्रीय विकास।',services_title:'व्यावसायिक क्षेत्र',service_1:'देशीय और अंतरराष्ट्रीय माल के लिए आयात-निर्यात सेवाएँ।',service_2:'साझेदार कनेक्शन और अंतरराष्ट्रीय व्यापार विकास।',service_3:'शिपिंग सहायता और कस्टम्स/आयात-निर्यात प्रक्रियाएँ।',partners_title:'साझेदार और बाज़ार',partners_desc:'मुख्य बाज़ारों के लिए लचीली सप्लाई चेन और सीमा-पार व्यापार सहयोग।',cap_title:'कंपनी क्षमताएँ',cap_1_title:'ऑर्डर संचालन',cap_1_desc:'प्रगति ट्रैकिंग, लॉजिस्टिक्स समन्वय और सीमा-पार ऑर्डर निष्पादन।',cap_2_title:'आपूर्तिकर्ता कनेक्शन',cap_2_desc:'सोर्सिंग, पार्टनर सत्यापन और सप्लाई चेन अनुकूलन।',cap_3_title:'दस्तावेज़ीकरण',cap_3_desc:'दस्तावेज़, आयात-निर्यात प्रक्रियाएँ और लॉजिस्टिक्स समन्वय सहायता।',cap_4_title:'बहुभाषी सहायता',cap_4_desc:'वियतनामी, चीनी और अंतरराष्ट्रीय ग्राहकों के साथ प्रभावी सहयोग।',form_title:'त्वरित संपर्क',form_name:'पूरा नाम',form_email:'ईमेल',form_message:'आपका संदेश',form_btn:'संदेश भेजें',form_note:'* यह फ़ॉर्म सीधे कंपनी सपोर्ट ईमेल vuhang@l38.vn पर भेजा जाएगा।',contact_title:'संपर्क',role_ceo:'निदेशक',role_cfo:'वित्त निदेशक',footer_desc:'आयात निर्यात सेवाएँ एवं ट्रेडिंग कंपनी लिमिटेड',footer_contact:'संपर्क',footer_market:'बाज़ार'}
};
const switcher=document.getElementById('languageSwitcher');
function setLanguage(lang){
 document.documentElement.lang=lang;
 document.querySelectorAll('[data-lang]').forEach(el=>{const k=el.dataset.lang;if(translations[lang]&&translations[lang][k]){el.textContent=translations[lang][k];}});
 document.querySelectorAll('[data-placeholder]').forEach(el=>{const k=el.dataset.placeholder;if(translations[lang]&&translations[lang][k]){el.placeholder=translations[lang][k];}});
 localStorage.setItem('l38_lang',lang);
}
switcher.addEventListener('change',e=>setLanguage(e.target.value));
setLanguage(localStorage.getItem('l38_lang')||'vi');
switcher.value=localStorage.getItem('l38_lang')||'vi';
